# =========================
# Base Image
# =========================
FROM mcr.microsoft.com/dotnet/sdk:10.0 AS base

# Install Node + Supervisor
RUN apt-get update && apt-get install -y \
    curl \
    supervisor \
    && curl -fsSL https://deb.nodesource.com/setup_22.x | bash - \
    && apt-get install -y nodejs \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

# Create app directory
WORKDIR /app

# =========================
# Frontend dependencies
# =========================
WORKDIR /app/FrontEnd
# Copy only package.json / package-lock.json to cache npm install
COPY FrontEnd/package*.json ./
RUN npm ci

# =========================
# Backend dependencies
# =========================
WORKDIR /app/Backend
COPY Backend/Backend.csproj ./
RUN dotnet restore

# =========================
# Supervisor config
# =========================
WORKDIR /app
COPY supervisord.dev.conf /etc/supervisor/conf.d/supervisord.conf

# Expose ports
EXPOSE 8080 4000

# Start Supervisor
CMD ["/usr/bin/supervisord", "-c", "/etc/supervisor/conf.d/supervisord.conf"]
